name: Lint & build

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        py_version: ["3.9", "3.10", "3.11", "3.12"]
        include:
          - os: windows-latest
            py_version: "3.9"
          - os: windows-latest
            py_version: "3.12"
          - os: macos-latest
            py_version: "3.9"
          - os: macos-latest
            py_version: "3.12"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev,cli]
        python -m pip install 'opencv-python-headless>=4.8,<4.9'
    - name: Lint
      run: |
        poe lint
    - name: Typecheck
      run: |
        poe type
    - name: Run tests
      run: |
        poe test

  build:
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip build poethepoet
        # Install package to generate version info
        python -m pip install --no-deps .
    - name: Build package
      run: |
        poe build
    - name: Save built package
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: |
          dist
    - name: Publish to PyPi
      if: ${{ github.ref_type	== 'tag' }}
      uses: pypa/gh-action-pypi-publish@release/v1
